### ISSUE TITLE
Remove separators between clauses in curly braces?

### ISSUE THREAD

**Issue by pigworker** [msp-strath/Mary#34]
One of the metarules in the design of Mary's syntax is that there is no composition by mere juxtaposition. This has to be the case if `[e1 e2]` is to be recognizably a list of length 2. As a result, we can be super-loose about layout.

    append([], ys) -> ys   append([x | xs], ys) -> [x | append(xs, ys)]

is just fine all on one line. Indeed, we make no distinction between newlines and other whitespace.

So now I'm asking myself why anonymous functions in curly braces separate clauses with `|`. There is no ambiguity in

    {p11,...,p1n -> e1   p21,...,p2n -> e2   ...   pm2,...pmn -> em}

with only whitespace separation.

I propose that we switch to whitespace separation. Any objections (technical or moral)?

**Comment by pigworker** [comment]
Ok, I think I'll make this change. Parsers, printers, documentation.

**Comment by gallais** [comment]
Fixed by 33a929040e93342c89943f59cdee0e9e9360efe6
