### ISSUE TITLE
Brace Deep Sections

### ISSUE THREAD

**Issue by pigworker** [msp-strath/Mary#65]
We should be able to construct abstractions on the fly by writing `_` in expressions which get abstracted in left-to-right order at theit closest enclosing curly braces. E.g.

    {"w" == _}

is the function which tests equality with "w".

    {_+3*_}(2,5) -> 17

It's a matter of turning the braces into extra args in a lambda.

    {x -> f(x,_)}

means

    {y,x -> f(x,y)}

It's a valuable source of brevity.

**Comment by gallais** [comment]
Fixed by #69
