### ISSUE TITLE
Replace circular programming in the top level `Env` by explicit recursion

### ISSUE THREAD

**Issue by pigworker** [msp-strath/Mary#7]
At the moment, we use Oxfordesque circular programming to construct an environment of recursive definitions, all in scope for each other. Although code runs ok, the resulting circular values are unserialisable. We could, instead, maintain a global environment of top level stuff, which would then not need to be stored in closures, or use some other explicit mapping from recursively defined names to their meanings.

**Comment by laMudri** [comment]
Fixed in 440b57054a81ebecf68b27c0a25b05ace400a370.
